java SyntaxChecker ../test cases/fail_01.minc   > ../test cases/output_fail_01.txt
java SyntaxChecker ../test cases/fail_01b.minc  > ../test cases/output_fail_01b.txt
java SyntaxChecker ../test cases/fail_02.minc   > ../test cases/output_fail_02.txt
java SyntaxChecker ../test cases/fail_02a.minc  > ../test cases/output_fail_02a.txt
java SyntaxChecker ../test cases/fail_02b.minc  > ../test cases/output_fail_02b.txt
java SyntaxChecker ../test cases/fail_02c.minc  > ../test cases/output_fail_02c.txt
java SyntaxChecker ../test cases/fail_02d.minc  > ../test cases/output_fail_02d.txt
java SyntaxChecker ../test cases/fail_02e.minc  > ../test cases/output_fail_02e.txt
java SyntaxChecker ../test cases/fail_03.minc   > ../test cases/output_fail_03.txt
java SyntaxChecker ../test cases/fail_03b.minc  > ../test cases/output_fail_03b.txt
java SyntaxChecker ../test cases/fail_04.minc   > ../test cases/output_fail_04.txt
java SyntaxChecker ../test cases/fail_05.minc   > ../test cases/output_fail_05.txt
java SyntaxChecker ../test cases/fail_06.minc   > ../test cases/output_fail_06.txt
java SyntaxChecker ../test cases/fail_06b.minc  > ../test cases/output_fail_06b.txt
java SyntaxChecker ../test cases/fail_07.minc   > ../test cases/output_fail_07.txt
java SyntaxChecker ../test cases/fail_08.minc   > ../test cases/output_fail_08.txt
java SyntaxChecker ../test cases/fail_08b.minc  > ../test cases/output_fail_08b.txt
java SyntaxChecker ../test cases/fail_09.minc   > ../test cases/output_fail_09.txt
java SyntaxChecker ../test cases/fail_09b.minc  > ../test cases/output_fail_09b.txt
java SyntaxChecker ../test cases/fail_10.minc   > ../test cases/output_fail_10.txt
java SyntaxChecker ../test cases/fail_11.minc   > ../test cases/output_fail_11.txt
java SyntaxChecker ../test cases/fail_12.minc   > ../test cases/output_fail_12.txt
java SyntaxChecker ../test cases/fail_13.minc   > ../test cases/output_fail_13.txt
java SyntaxChecker ../test cases/fail_14.minc   > ../test cases/output_fail_14.txt
java SyntaxChecker ../test cases/fail_14b.minc  > ../test cases/output_fail_14b.txt
java SyntaxChecker ../test cases/fail_15.minc   > ../test cases/output_fail_15.txt
java SyntaxChecker ../test cases/fail_15b.minc  > ../test cases/output_fail_15b.txt
java SyntaxChecker ../test cases/fail_15c.minc  > ../test cases/output_fail_15c.txt

java SyntaxChecker ../test cases/succ_01.minc   > ../test cases/output_succ_01.txt
java SyntaxChecker ../test cases/succ_02.minc   > ../test cases/output_succ_02.txt
java SyntaxChecker ../test cases/succ_03.minc   > ../test cases/output_succ_03.txt
java SyntaxChecker ../test cases/succ_04.minc   > ../test cases/output_succ_04.txt
java SyntaxChecker ../test cases/succ_05.minc   > ../test cases/output_succ_05.txt
java SyntaxChecker ../test cases/succ_06.minc   > ../test cases/output_succ_06.txt
java SyntaxChecker ../test cases/succ_07.minc   > ../test cases/output_succ_07.txt
java SyntaxChecker ../test cases/succ_08.minc   > ../test cases/output_succ_08.txt
java SyntaxChecker ../test cases/succ_09.minc   > ../test cases/output_succ_09.txt
java SyntaxChecker ../test cases/succ_10.minc   > ../test cases/output_succ_10.txt
java SyntaxChecker ../test cases/succ_11.minc   > ../test cases/output_succ_11.txt
java SyntaxChecker ../test cases/succ_12.minc   > ../test cases/output_succ_12.txt
java SyntaxChecker ../test cases/succ_13.minc   > ../test cases/output_succ_13.txt
java SyntaxChecker ../test cases/succ_14.minc   > ../test cases/output_succ_14.txt
java SyntaxChecker ../test cases/succ_15.minc   > ../test cases/output_succ_15.txt
java SyntaxChecker ../test cases/succ_16.minc   > ../test cases/output_succ_16.txt
